version: '3.9'
services:
  python:
    image: akraradets/bloodglucose-python:v0.0.1
    build: 
      context: .
      dockerfile: python.Dockerfile
    environment:
      - DISPLAY=${HOSTNAME}:0
    volumes:
      - ./projects/:/root/projects
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - venv:/root/projects/python/.venv
      - vscode-python:/root/.vscode-server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  latex:
    image: akraradets/bloodglucose-latex:v0.0.1
    build: 
      context: .
      dockerfile: latex.Dockerfile
    volumes:
      - ./projects/:/root/projects
      - vscode-latex:/root/.vscode-server

volumes:
  venv:
  vscode-latex:
  vscode-python: