version: '3.9'
services:
  python:
    build: 
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./projects/:/root/projects
      - vscode-python:/root/.vscode-server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  latex:
    image: bloodglucose-latex
    build: 
      context: .
      dockerfile: latex.Dockerfile
    volumes:
      - ./projects/:/root/projects
      - vscode-latex:/root/.vscode-server

volumes:
  vscode-latex:
  vscode-python: